### ISSUE TITLE
Mesh Leveling on Artist D Pro

### ISSUE THREAD

**Issue by KevS3** [TwinkieXLII/ArtistD-Pro#1]
Hi Mark, have you tried enabling mesh leveling on artist D Pro? Will you be planning to enable it on the D Pro as well?

**Comment by KevS3** [comment]
Sorry to add in the issue section. Couldn't find any where else to do it in github. Thank you in advance!

**Comment by TwinkieXLII** [comment]
Yes this has been added Today

**Comment by KevS3** [comment]
Awesome! Looking great! Thank you for your awesome work!
